import Image from "next/image";
import React from "react";
import { PublicFooter } from "../PublicFooter";
import { MoreMenu } from "./MoreMenu";

const nav = [["How It Works", "/how-it-works"], ["Platform", "/platform"], ["Example Report", "/example-report"], ["Research", "/research"], ["About", "/about"]];

type Card = { title: string; body: string };

export function PublicPage({ eyebrow, title, intro, cards, cta = true, children }: { eyebrow: string; title: string; intro: string; cards?: Card[]; cta?: boolean; children?: React.ReactNode }) {
  return <div className="min-h-screen bg-[#FAFAF8] text-[#1A1A1A]" style={{ fontFamily: "Inter, Arial, sans-serif" }}><header className="sticky top-0 z-50 h-[72px] bg-[#1A2A4A] text-white shadow-sm"><nav className="mx-auto flex h-full max-w-[1280px] items-center justify-between px-5 lg:px-8" aria-label="Public navigation"><a href="/" aria-label="ROOTS-AI home"><Image src="/assets/branding/logo.png" alt="ROOTS-AI" width={126} height={30} className="h-8 w-auto object-contain" priority /></a><div className="hidden items-center gap-7 text-sm font-medium md:flex">{nav.map(([label, href]) => <a key={href} href={href} className="min-h-11 inline-flex items-center hover:underline">{label}</a>)}<MoreMenu className="text-sm font-medium text-[#1A1A1A]" /></div><a href="/assessment" className="inline-flex min-h-11 items-center rounded-lg bg-white px-5 text-sm font-bold text-[#1A2A4A] hover:bg-[#F3F4F6]">Start Your Assessment</a></nav></header><main><section className="mx-auto max-w-[1200px] px-5 pb-14 pt-16 sm:px-8 lg:pt-20"><p className="text-sm font-bold uppercase tracking-wide text-[#2A8C88]">{eyebrow}</p><h1 className="mt-5 max-w-5xl text-5xl font-bold leading-tight text-[#1A2A4A] sm:text-6xl">{title}</h1><p className="mt-6 max-w-3xl text-lg leading-7 text-[#6B7280]">{intro}</p>{cta ? <a href="/assessment" className="mt-8 inline-flex min-h-11 items-center rounded-lg bg-[#1A2A4A] px-6 text-sm font-bold text-white hover:bg-[#2A4060]">Start Your Assessment</a> : null}</section>{cards ? <section className="mx-auto max-w-[1200px] px-5 pb-20 sm:px-8"><div className="grid gap-6 md:grid-cols-2 lg:grid-cols-3">{cards.map((card) => <article key={card.title} className="min-h-[150px] rounded-xl border border-[#D8DEE8] bg-white p-6"><h2 className="text-lg font-bold text-[#1A2A4A]">{card.title}</h2><p className="mt-3 text-base leading-6 text-[#6B7280]">{card.body}</p></article>)}</div></section> : null}{children}</main><PublicFooter /></div>;
}
