/* ============================================================================
 * ROOTS-AI™ — Milestone 2 · C-01 canonical question bank — DERIVED, NOT TYPED
 * ----------------------------------------------------------------------------
 * Every question, option, label, order and burden value below is DERIVED at
 * module load from the transcribed controlled tables in lib/assessment/
 * controlled/ (generated by `npm run build:controlled` from the C-01 and C-02
 * workbooks). Nothing on this page is authored content: no prompt, label,
 * point value or domain code is written here, so none can be mistyped, and a
 * reviewer can trace any string on screen back to the row it is built from.
 *
 * Why derived instead of transcribed by hand: the previous template expected a
 * person to re-type 73 questions, 171 options and 238 point values. Hand
 * copying is how a questionnaire ends up looking canonical and scoring wrong.
 * Deriving removes the step, and the derivation is strict — it throws rather
 * than emit a shorter bank, a silently missing option, or a value parsed out of
 * a cell that does not hold one.
 *
 * Division of authority, enforced here rather than only documented:
 *   C-01 (Questions, Option_Sets, Modules) — WHAT is asked, in what order, with
 *       which labels, and whether an answer is required or may be N/A.
 *   C-02 (Question_Mapping, Option_Points) — WHICH domain a question feeds and
 *       WHAT its answer is worth. A contextual question has no C-02 row at all
 *       (Blueprint §1: the 33 MUST NOT affect calculations), so the isolation is
 *       structural: its rawBurdenValue can only ever be null.
 *
 * One trap this file exists to defuse: C-01's `stored_value_or_points` is NOT
 * always the burden value. For the two reverse-scored questions (Q26, Q28 —
 * C-02 Question_Mapping reverse_scored=1) C-01 stores the raw frequency
 * (NVR=0 … ALW=4) while C-02 stores the burden points (NVR=4 … ALW=0). C-02's
 * Option_Points are therefore ALREADY direction-adjusted: the engine must use
 * `rawBurdenValue` as-is and never re-apply a direction. `storedValue` keeps
 * C-01's own cell so the difference stays visible instead of being silently
 * reconciled.
 * ==========================================================================*/

import {
  CANONICAL_MODULE_COUNT,
  CANONICAL_QUESTION_COUNT,
  QUESTIONNAIRE_VERSION,
} from "./canonical-constants";
import {
  C01_MODULE_ROWS,
  C01_OPTION_SET_ROWS,
  C01_QUESTION_ROWS,
  C02_OPTION_POINT_ROWS,
  C02_QUESTION_MAP_ROWS,
  CONTROLLED_C01,
} from "./controlled";
import type { CanonicalDomainCode } from "./canonical-constants";
import type { C01OptionRow, C01QuestionRow, C02OptionPointRow, C02QuestionMapRow } from "./controlled";
import type { StructureViolation, StructureViolationCode } from "./invariants";
import type {
  CanonicalQuestionBank,
  ControlledSourceProvenance,
  ModuleDefinition,
  ModuleIndex,
  MultiSelectRule,
  QuestionDefinition,
  QuestionNumber,
  QuestionOptionDefinition,
  QuestionResponseKind,
} from "./types";

/* ---------------------------------------------------------------------------
 * Branding helpers.
 * The `QuestionNumber` / `ModuleIndex` brands exist so a loop counter or an
 * array index cannot be passed where a canonical number is required. These are
 * the only sanctioned escape hatches. Range checking is invariants.ts's job,
 * where every breach can be reported at once instead of throwing on the first.
 * -------------------------------------------------------------------------*/
export const asQuestionNumber = (n: number): QuestionNumber => n as QuestionNumber;
export const asModuleIndex = (n: number): ModuleIndex => n as ModuleIndex;

/* ---------------------------------------------------------------------------
 * Parsing of controlled cells. Both workbooks store numbers as TEXT, so text is
 * what arrives here; an empty cell stays "no value" and never becomes 0. A cell
 * that should hold a number and does not is a transcription failure, not a
 * data-entry problem — it throws, so the build breaks instead of the
 * questionnaire drifting.
 * -------------------------------------------------------------------------*/
const controlledNumber = (text: string, context: string): number | null => {
  const trimmed = text.trim();
  if (trimmed === "") return null;
  const value = Number(trimmed);
  if (!Number.isFinite(value)) {
    throw new Error(`${context}: "${text}" is not a number`);
  }
  return value;
};

const controlledInteger = (text: string, context: string): number => {
  const value = controlledNumber(text, context);
  if (value === null || !Number.isInteger(value)) {
    throw new Error(`${context}: "${text}" is not a whole number`);
  }
  return value;
};

/** Both workbooks mark yes/no columns with "1" / "0", never with words. */
const yes = (text: string): boolean => text.trim() === "1";

/** Separator no option id or question id contains — U+241F SYMBOL FOR. */
const KEY_SEPARATOR = "\u241F";
const optionKey = (questionId: string, optionId: string): string =>
  `${questionId}${KEY_SEPARATOR}${optionId}`;

/* ---------------------------------------------------------------------------
 * Indexes over the controlled rows. Row order is preserved on every read, so
 * the loops below walk the sheets in the order the workbook lists them.
 * -------------------------------------------------------------------------*/
const optionRowsBySet = new Map<string, readonly C01OptionRow[]>();
for (const row of C01_OPTION_SET_ROWS) {
  const list = optionRowsBySet.get(row.option_set_id) as C01OptionRow[] | undefined;
  if (list === undefined) optionRowsBySet.set(row.option_set_id, [row]);
  else list.push(row);
}

const pointsByOption = new Map<string, C02OptionPointRow>();
for (const row of C02_OPTION_POINT_ROWS) {
  const key = optionKey(row.question_id, row.option_id);
  if (pointsByOption.has(key)) {
    throw new Error(`C-02 Option_Points lists ${key} more than once`);
  }
  pointsByOption.set(key, row);
}

const mapByQuestion = new Map<string, C02QuestionMapRow>();
for (const row of C02_QUESTION_MAP_ROWS) {
  if (mapByQuestion.has(row.question_id)) {
    throw new Error(`C-02 Question_Mapping lists ${row.question_id} more than once`);
  }
  mapByQuestion.set(row.question_id, row);
}

/* ---------------------------------------------------------------------------
 * Row-count and version gate. The generator already proves these counts against
 * each workbook's own README and QA_Checks sheets; restating them here means a
 * truncated regeneration cannot produce a bank that merely looks shorter, and a
 * version pin that no longer matches the transcribed workbook fails at import.
 * -------------------------------------------------------------------------*/
if (C01_QUESTION_ROWS.length !== CANONICAL_QUESTION_COUNT) {
  throw new Error(
    `C-01 transcription holds ${C01_QUESTION_ROWS.length} questions, ` +
      `expected ${CANONICAL_QUESTION_COUNT}. Re-run npm run build:controlled.`,
  );
}
if (C01_MODULE_ROWS.length !== CANONICAL_MODULE_COUNT) {
  throw new Error(
    `C-01 transcription holds ${C01_MODULE_ROWS.length} modules, ` +
      `expected ${CANONICAL_MODULE_COUNT}. Re-run npm run build:controlled.`,
  );
}
if (!QUESTIONNAIRE_VERSION.includes(CONTROLLED_C01.version)) {
  throw new Error(
    `QUESTIONNAIRE_VERSION (${QUESTIONNAIRE_VERSION}) does not pin the transcribed ` +
      `workbook version (${CONTROLLED_C01.version}). Change canonical-constants.ts ` +
      `only when a new controlled C-01 is issued.`,
  );
}

/* ---------------------------------------------------------------------------
 * Options. C-01 Option_Sets supplies the id, label and order; C-02 Option_Points
 * supplies the worth. They are joined on (question_id, option_id) and the join is
 * PROVED rather than assumed: the two sheets must state the same label, so a set
 * joined to the wrong question fails loudly instead of becoming a plausible but
 * wrong point value.
 * -------------------------------------------------------------------------*/
function optionsFor(
  row: C01QuestionRow,
  scored: boolean,
  multiSelect: boolean,
): readonly QuestionOptionDefinition[] {
  const setRows = optionRowsBySet.get(row.option_set_id) ?? [];
  if (row.option_set_id !== "" && setRows.length === 0) {
    throw new Error(
      `C-01 Questions.${row.question_id} names option set "${row.option_set_id}" ` +
        "which Option_Sets never defines",
    );
  }
  const options: QuestionOptionDefinition[] = [];
  for (const option of setRows) {
    const where = `${row.question_id}/${option.option_id}`;
    const order = controlledInteger(
      option.option_order,
      `C-01 Option_Sets ${where} option_order`,
    );
    const storedValue = option.stored_value_or_points === ""
      ? null
      : option.stored_value_or_points;
    const points = pointsByOption.get(optionKey(row.question_id, option.option_id));

    if (points === undefined) {
      if (scored) {
        throw new Error(
          `C-02 Option_Points has no row for scored option ${where}: a scored ` +
            "option cannot be silently worth nothing",
        );
      }
      // Contextual option. C-01 may still carry a value for it — Q72's
      // confidence bands (25/50/75/100) feed SC-008 — but never burden points.
      // Mutual exclusion is a multi-select law (C-01 VAL-006); a single-select
      // N/A is already exclusive by being the only choice made.
      options.push({
        optionId: option.option_id,
        label: option.display_label,
        order,
        rawBurdenValue: null,
        storedValue,
        isExclusiveNoneOption: multiSelect && yes(option.is_na),
        countsTowardScore: false,
      });
      continue;
    }

    if (!scored) {
      throw new Error(
        `C-02 Option_Points awards burden points to ${where}, but C-01 marks ` +
        `${row.question_id} contextual — Blueprint §1 keeps it out of the calculation`,
      );
    }
    if (points.display_label !== option.display_label) {
      throw new Error(
        `C-01 and C-02 state different labels for ${where}: ` +
        `|${option.display_label}| vs |${points.display_label}| — an option set ` +
        "has been joined to the wrong question",
      );
    }
    const excludedAsNa = yes(points.excluded_as_na);
    const burden = controlledNumber(
      points.burden_points,
      `C-02 Option_Points ${where} burden_points`,
    );
    if (burden === null && !excludedAsNa) {
      throw new Error(
        `C-02 Option_Points ${where} carries neither burden_points nor excluded_as_na`,
      );
    }
    options.push({
      optionId: option.option_id,
      label: option.display_label,
      order,
      // Verbatim C-02, already direction-adjusted for the reverse-scored pair.
      rawBurdenValue: burden,
      storedValue,
      isExclusiveNoneOption: false,
      countsTowardScore: !excludedAsNa,
    });
  }
  return options;
}

/* ---------------------------------------------------------------------------
 * Response kinds — the eight codes C-01 writes in its own question_type column
 * (integer 1, decimal 3, decimal_with_unit 1, integer_scale 2, likert 37,
 * single_select 23, multi_select 5, free_text 1 = 73). An unrecognised code
 * throws instead of being dropped: a new question type is a deliberate change to
 * the model, not something a data file may slip past.
 * -------------------------------------------------------------------------*/
const RESPONSE_KINDS: readonly QuestionResponseKind[] = [
  "integer",
  "decimal",
  "decimal_with_unit",
  "integer_scale",
  "single_select",
  "likert",
  "multi_select",
  "free_text",
];

function responseKindOf(row: C01QuestionRow): QuestionResponseKind {
  const kind = RESPONSE_KINDS.find((candidate) => candidate === row.question_type);
  if (kind === undefined) {
    throw new Error(
      `C-01 Questions ${row.question_id} has question_type "${row.question_type}", ` +
        "which QuestionResponseKind does not model. Extend types.ts deliberately " +
        "rather than dropping the question.",
    );
  }
  return kind;
}

/* ---------------------------------------------------------------------------
 * Module placement. C-01 states a module's order twice — once in Modules, once on
 * every question — so the two are reconciled here before anything is built: a
 * disagreement would silently move questions between modules.
 * -------------------------------------------------------------------------*/
const moduleRowById = new Map(C01_MODULE_ROWS.map((row) => [row.module_id, row]));
const moduleIndexById = new Map<string, number>();
for (const row of C01_QUESTION_ROWS) {
  const moduleRow = moduleRowById.get(row.module_id);
  if (moduleRow === undefined) {
    throw new Error(
      `C-01 Questions ${row.question_id} belongs to ${row.module_id}, which the ` +
        "Modules sheet never declares",
    );
  }
  const declared = controlledInteger(
    moduleRow.module_order,
    `C-01 Modules ${row.module_id} module_order`,
  );
  const onQuestion = controlledInteger(
    row.module_order,
    `C-01 Questions ${row.question_id} module_order`,
  );
  if (declared !== onQuestion) {
    throw new Error(
      `C-01 module ${row.module_id} is order ${declared} in Modules but ${onQuestion} ` +
        `on question ${row.question_id}`,
    );
  }
  moduleIndexById.set(row.module_id, declared);
}

/* ---------------------------------------------------------------------------
 * The 73 canonical questions, in C-01's own row order. The generator writes rows
 * in sheet order and the workbook's QA_Checks prove the range Q1..Q73, so row
 * order IS canonical order; question_order is still read and checked rather than
 * inferred from position.
 * -------------------------------------------------------------------------*/
function domainCodeFor(
  row: C01QuestionRow,
  scored: boolean,
): CanonicalDomainCode | null {
  const mapping = mapByQuestion.get(row.question_id);
  if (!scored) {
    if (mapping !== undefined) {
      throw new Error(
        `C-02 Question_Mapping lists ${row.question_id} under ${mapping.domain_id}, ` +
          `but C-01 marks it contextual — Blueprint §1 keeps the 33 out of the ` +
          "calculation",
      );
    }
    return null;
  }
  if (mapping === undefined) {
    throw new Error(
      `C-02 Question_Mapping has no row for scored question ${row.question_id}`,
    );
  }
  // The code is C-02's own text. Whether it is one of the seven canonical codes
  // is invariants.ts's job, where a breach is reported alongside the others
  // instead of throwing on its own.
  return mapping.domain_id as CanonicalDomainCode;
}

function multiSelectRuleFor(
  row: C01QuestionRow,
  multiSelect: boolean,
  options: readonly QuestionOptionDefinition[],
): MultiSelectRule | null {
  if (!multiSelect) return null;
  const exclusive = options.filter((option) => option.isExclusiveNoneOption);
  if (exclusive.length !== 1) {
    throw new Error(
      `C-01 gives multi-select ${row.question_id} ${exclusive.length} N/A options; ` +
        "VAL-006 requires exactly one mutually exclusive None/N/A option",
    );
  }
  return {
    // VAL-006: "One or more approved option IDs … empty array invalid".
    minSelections: 1,
    // C-01 sets no upper bound on how many may be chosen.
    maxSelections: null,
    exclusiveNoneOptionId: exclusive[0].optionId,
    emptySelectionIsValid: false,
  };
}

export const C01_QUESTIONS: readonly QuestionDefinition[] = C01_QUESTION_ROWS.map(
  (row): QuestionDefinition => {
    const scored = yes(row.scoring_eligible);
    const multiSelect = row.question_type === "multi_select";
    const options = optionsFor(row, scored, multiSelect);
    return {
      questionId: row.question_id,
      questionNumber: asQuestionNumber(
        controlledInteger(row.question_order, `C-01 Questions ${row.question_id} question_order`),
      ),
      moduleIndex: asModuleIndex(moduleIndexById.get(row.module_id) as number),
      /** Verbatim C-01 prompt — never re-worded, never re-cased. */
      prompt: row.question_text,
      helperText: row.help_text === "" ? null : row.help_text,
      responseKind: responseKindOf(row),
      requirement: yes(row.required) ? "required" : "optional",
      eligibility: scored ? "scored" : "contextual",
      domainCode: domainCodeFor(row, scored),
      naPolicy: yes(row.allow_na) ? "explicit_only" : "not_permitted",
      optionSetId: row.option_set_id === "" ? null : row.option_set_id,
      /** Verbatim C-01 conditional_logic; "NONE" for all 73 in v1.0.1. */
      conditionalLogic: row.conditional_logic,
      options,
      multiSelectRule: multiSelectRuleFor(row, multiSelect, options),
    };
  },
);

/* ---------------------------------------------------------------------------
 * The 13 ordered modules. Title, purpose and question_range are C-01's own text;
 * the roster is derived from the questions themselves, which is what lets
 * invariants.ts compare the derived roster against C-01's declared range and
 * report a divergence instead of hiding one.
 * -------------------------------------------------------------------------*/
const questionNumbersByModuleIndex = new Map<number, number[]>();
for (const question of C01_QUESTIONS) {
  const list = questionNumbersByModuleIndex.get(question.moduleIndex) ?? [];
  list.push(question.questionNumber);
  questionNumbersByModuleIndex.set(question.moduleIndex, list);
}

export const C01_MODULES: readonly ModuleDefinition[] = C01_MODULE_ROWS.map(
  (row): ModuleDefinition => {
    const moduleIndex = controlledInteger(
      row.module_order,
      `C-01 Modules ${row.module_id} module_order`,
    );
    const numbers = [...(questionNumbersByModuleIndex.get(moduleIndex) ?? [])].sort(
      (a, b) => a - b,
    );
    return {
      moduleIndex: asModuleIndex(moduleIndex),
      moduleCode: row.module_id,
      title: row.module_title,
      // C-01 states no participant-facing module introduction. Its `purpose`
      // column is internal metadata (e.g. "Contextual only.") and is carried as
      // such, so nobody renders it to a participant by reaching for introText.
      introText: null,
      purpose: row.purpose,
      questionRange: row.question_range,
      questionNumbers: numbers,
    };
  },
);

/* ---------------------------------------------------------------------------
 * Provenance — taken from the generated audit trail, i.e. from the bytes the
 * transcription actually came from. `receivedOn` stays null on purpose: the
 * received date belongs to the delivery record, and embedding it here would make
 * regeneration non-deterministic.
 * -------------------------------------------------------------------------*/
export const C01_SOURCE: ControlledSourceProvenance = {
  documentTitle: "C-01 Canonical Question Bank",
  version: QUESTIONNAIRE_VERSION,
  fileSha256: CONTROLLED_C01.packageSha256,
  contentSha256: CONTROLLED_C01.contentSha256,
  receivedOn: null,
};

/* ---------------------------------------------------------------------------
 * The assembled bank.
 * `populated` is computed, not asserted: it stays an honest gate that would flip
 * back to false if a regeneration ever produced a shorter table, instead of a
 * literal `true` that could outlive the data it describes.
 * -------------------------------------------------------------------------*/
export const QUESTION_BANK: CanonicalQuestionBank = {
  source: C01_SOURCE,
  populated:
    C01_QUESTIONS.length === CANONICAL_QUESTION_COUNT &&
    C01_MODULES.length === CANONICAL_MODULE_COUNT,
  modules: C01_MODULES,
  questions: C01_QUESTIONS,
};

/* ---------------------------------------------------------------------------
 * Readiness gate.
 * An empty or short bank is structurally well-formed, so a naive validator would
 * call it valid and M2 would "pass" with fewer than 73 questions. `source
 * unpopulated` is reported first and short-circuits: nothing downstream may treat
 * a short bank as a legitimate questionnaire.
 * -------------------------------------------------------------------------*/
export const C01_UNPOPULATED_CODE: StructureViolationCode = "SOURCE_UNPOPULATED";

export function c01MissingSourceViolations(): readonly StructureViolation[] {
  const detail =
    `${CONTROLLED_C01.fileName} is transcribed into lib/assessment/controlled/, but ` +
    `only ${C01_QUESTIONS.length} of ${CANONICAL_QUESTION_COUNT} questions and ` +
    `${C01_MODULES.length} of ${CANONICAL_MODULE_COUNT} modules were derived from it. ` +
    "Re-run npm run build:controlled; never author question content in this file.";
  return QUESTION_BANK.populated
    ? []
    : [{ code: C01_UNPOPULATED_CODE, subject: "C-01 question bank", detail }];
}

/** Index lookups used by validation, scoring and resume. */
export const questionById: ReadonlyMap<string, QuestionDefinition> = new Map(
  C01_QUESTIONS.map((question) => [question.questionId, question]),
);

export const questionsByModule: ReadonlyMap<number, readonly QuestionDefinition[]> = new Map(
  C01_MODULES.map((module) => [
    module.moduleIndex,
    C01_QUESTIONS.filter((question) => question.moduleIndex === module.moduleIndex),
  ]),
);

/** Question number → definition. Resume and validation address answers by number. */
export const questionByNumber: ReadonlyMap<number, QuestionDefinition> = new Map(
  C01_QUESTIONS.map((question) => [question.questionNumber, question]),
);

/** Option id → definition, within one question. Answers arrive as option ids. */
export function optionById(
  questionId: string,
  optionId: string,
): QuestionOptionDefinition | undefined {
  return questionById.get(questionId)?.options.find((option) => option.optionId === optionId);
}
